import type { Theme } from '../style.ts';

export const contrast: Theme = {
  name: 'contrast',
  styles: {
    default: {},
    heading: { bold: true, fg: '97' },
    subheading: { bold: true, fg: '96' },
    code: { fg: '92' },
    'code.block': { fg: '93' },
    'diff.added': { bg: '42', fg: '97' },
    'diff.removed': { bg: '41', fg: '97' },
    'diff.header': { dim: true, fg: '90' },
    'status.info': { fg: '96' },
    'status.error': { fg: '91', bold: true },
    'status.warning': { fg: '93', bold: true },
    'status.success': { fg: '92', bold: true },
    muted: { dim: true },
    inverse: { inverse: true },
    bold: { bold: true },
    dim: { dim: true },
    italic: { italic: true },
    underline: { underline: true },
    prompt: { fg: '92', bold: true },
    'user.role': { fg: '94', bold: true },
    'assistant.role': { fg: '92', bold: true },
    'system.role': { fg: '90', bold: true },
    'tool.name': { fg: '95', bold: true },
    'completion.selected': { bg: '44', fg: '97' },
    link: { fg: '94', underline: true, bold: true },
    'title.bar': { bg: '44', fg: '97', bold: true },
    'status.bar': { inverse: true },
  },
};
