import type { Theme } from '../style.ts';

export const dark: Theme = {
  name: 'dark',
  styles: {
    default: {},
    heading: { bold: true, fg: '97' },
    subheading: { bold: true, fg: '96' },
    code: { fg: '92' },
    'code.block': { fg: '33' },
    'diff.added': { fg: '32' },
    'diff.removed': { fg: '31' },
    'diff.header': { dim: true, fg: '90' },
    'status.info': { fg: '36' },
    'status.error': { fg: '31' },
    'status.warning': { fg: '33' },
    'status.success': { fg: '32' },
    muted: { dim: true },
    inverse: { inverse: true },
    bold: { bold: true },
    dim: { dim: true },
    italic: { italic: true },
    underline: { underline: true },
    prompt: { fg: '92' },
    'user.role': { fg: '94', bold: true },
    'assistant.role': { fg: '92', bold: true },
    'system.role': { fg: '90', bold: true },
    'tool.name': { fg: '95' },
    'completion.selected': { inverse: true },
    link: { fg: '94', underline: true },
    'title.bar': { bg: '44', fg: '97', bold: true },
    'status.bar': { inverse: true },
  },
};
