CREATE TABLE IF NOT EXISTS code_projects (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, root_path TEXT NOT NULL, language_stats TEXT, node_count INTEGER NOT NULL DEFAULT 0, edge_count INTEGER NOT NULL DEFAULT 0, indexed_at TEXT NOT NULL DEFAULT (datetime('now')), git_commit TEXT, version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS code_nodes (id INTEGER PRIMARY KEY AUTOINCREMENT, project_id INTEGER NOT NULL REFERENCES code_projects(id) ON DELETE CASCADE, label TEXT NOT NULL, name TEXT NOT NULL, qualified_name TEXT NOT NULL, file_path TEXT, line_start INTEGER, line_end INTEGER, signature TEXT, return_type TEXT, language TEXT, is_exported INTEGER NOT NULL DEFAULT 0, complexity INTEGER NOT NULL DEFAULT 0, decorators TEXT, metadata TEXT, content_hash TEXT, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE INDEX IF NOT EXISTS idx_code_nodes_project ON code_nodes(project_id);
CREATE INDEX IF NOT EXISTS idx_code_nodes_label ON code_nodes(label);
CREATE INDEX IF NOT EXISTS idx_code_nodes_qname ON code_nodes(qualified_name);
CREATE INDEX IF NOT EXISTS idx_code_nodes_name ON code_nodes(name);
CREATE INDEX IF NOT EXISTS idx_code_nodes_file ON code_nodes(file_path);
CREATE INDEX IF NOT EXISTS idx_code_nodes_lang ON code_nodes(language);
CREATE INDEX IF NOT EXISTS idx_code_nodes_deadcode ON code_nodes(project_id, label, is_exported, complexity);
CREATE TABLE IF NOT EXISTS code_edges (id INTEGER PRIMARY KEY AUTOINCREMENT, project_id INTEGER NOT NULL REFERENCES code_projects(id) ON DELETE CASCADE, type TEXT NOT NULL, source_id INTEGER NOT NULL REFERENCES code_nodes(id) ON DELETE CASCADE, target_id INTEGER NOT NULL REFERENCES code_nodes(id) ON DELETE CASCADE, confidence REAL NOT NULL DEFAULT 1.0, call_line INTEGER, arg_to_param TEXT, metadata TEXT, created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE INDEX IF NOT EXISTS idx_code_edges_project ON code_edges(project_id);
CREATE INDEX IF NOT EXISTS idx_code_edges_type ON code_edges(type);
CREATE INDEX IF NOT EXISTS idx_code_edges_source ON code_edges(source_id);
CREATE INDEX IF NOT EXISTS idx_code_edges_target ON code_edges(target_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_code_edges_unique ON code_edges(project_id, source_id, target_id, type);
CREATE TABLE IF NOT EXISTS code_file_hashes (project_id INTEGER NOT NULL REFERENCES code_projects(id) ON DELETE CASCADE, file_path TEXT NOT NULL, hash TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT (datetime('now')), PRIMARY KEY (project_id, file_path));
CREATE INDEX IF NOT EXISTS idx_code_file_hashes_hash ON code_file_hashes(hash);
CREATE TABLE IF NOT EXISTS code_communities (id INTEGER PRIMARY KEY AUTOINCREMENT, project_id INTEGER NOT NULL REFERENCES code_projects(id) ON DELETE CASCADE, name TEXT NOT NULL, member_count INTEGER NOT NULL DEFAULT 0, internal_density REAL NOT NULL DEFAULT 0.0, created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE INDEX IF NOT EXISTS idx_code_communities_project ON code_communities(project_id);
CREATE VIRTUAL TABLE IF NOT EXISTS code_nodes_fts USING fts5(name, qualified_name, signature, file_path, content='code_nodes', content_rowid='id', tokenize='unicode61');
