import type { ToolCapability } from '../types.ts';

export const CHROME_BRIDGE_CAPABILITIES: Record<string, ToolCapability[]> = {
  get_status: [],
  get_tabs: [],
  create_tab: ['network:fetch'],
  navigate: ['network:fetch'],
  tab_action: ['network:fetch'],
  wait_for_navigation: [],
  get_frames: [],
  screenshot: ['computer:screenshot'],

  click: [],
  type_text: ['computer:keyboard'],
  fill_form: ['computer:keyboard'],
  hover: ['computer:mouse'],
  press_key: ['computer:keyboard'],
  scroll_to: [],
  scroll_until: [],
  drag_and_drop: ['computer:mouse'],
  upload_file: ['fs:read'],
  dismiss_overlays: [],
  handle_dialogs: [],
  clipboard: ['computer:control'],

  read_page: [],
  get_page_info: [],
  query_dom: [],
  modify_dom: [],
  find_text: [],
  get_interactives: [],
  inject_css: [],
  highlight_elements: [],
  watch_dom: [],
  measure_spacing: [],

  wait_for_element: [],
  wait_for_function: [],
  wait_for_network_idle: [],

  execute_js: [],
  read_console: [],
  monitor_network: ['network:fetch'],
  monitor_websocket: ['network:fetch'],
  network_rules: ['network:fetch'],
  get_performance: [],
  web_vitals: [],
  list_event_listeners: [],

  element_screenshot: ['computer:screenshot'],
  full_page_screenshot: ['computer:screenshot'],
  screenshot_diff: ['computer:screenshot'],
  viewport_resize: [],
  set_zoom: [],
  emulate_media: [],
  set_geolocation: [],

  accessibility_audit: [],
  seo_audit: [],
  security_headers: [],
  check_links: ['network:fetch'],
  unused_css: [],
  extract_table: [],

  get_storage: [],
  set_storage: [],
  session_fixture: [],
  http_auth: [],

  save_page: ['fs:write'],
  manage_downloads: ['fs:write'],
};
