/**
 * CortexPrism WASM Plugin SDK — TypeScript Client Library
 *
 * Use this library to build WASM plugins for CortexPrism.
 * Provides typed wrappers for all host functions and tool registration.
 *
 * Usage:
 *   import { definePlugin, defineTool } from './sdk/client.ts';
 *
 *   const echo = defineTool({
 *     name: 'echo',
 *     description: 'Echoes back the input',
 *     params: [{ name: 'message', type: 'string', description: 'The message', required: true }],
 *     execute(args) {
 *       return { echoed: args.message };
 *     },
 *   });
 *
 *   export default definePlugin({ name: 'my-plugin', version: '1.0.0', tools: [echo] });
 */

export interface ToolParam {
  name: string;
  type: 'string' | 'number' | 'boolean' | 'object' | 'array';
  description: string;
  required?: boolean;
}

export interface ToolDefinition {
  name: string;
  description: string;
  params: ToolParam[];
}

export interface PluginConfig {
  name: string;
  version: string;
  tools: ToolDefinition[];
}

export interface WasmHost {
  alloc(size: number): number;
  log(msg: string): void;
  getConfig(key: string): string | null;
  setState(key: string, value: string): void;
  getState(key: string): string | null;
  httpRequest(
    method: string,
    url: string,
    body?: string,
    headers?: Record<string, string>,
  ): { status: number; body: string };
  getAbiVersion(): number;
  getTimeMs(): number;
  random(len: number): Uint8Array;
}

const encoder = new TextEncoder();
const decoder = new TextDecoder();

function readString(memory: WebAssembly.Memory, ptr: number, len: number): string {
  try {
    return decoder.decode(new Uint8Array(memory.buffer, ptr, Math.min(len, 65536)));
  } catch {
    return '';
  }
}

function writeString(
  memory: WebAssembly.Memory,
  str: string,
  outPtr: number,
  outLenPtr: number,
): void {
  const encoded = encoder.encode(str);
  const maxLen = Math.min(encoded.length, 65536 - 8);
  const dest = new Uint8Array(memory.buffer, outPtr, maxLen);
  dest.set(encoded.subarray(0, maxLen));
  new Uint32Array(memory.buffer, outLenPtr, 1)[0] = maxLen;
}

export function createWasmHost(memory: WebAssembly.Memory): WasmHost {
  return {
    alloc(size: number): number {
      const ptr = 0x20000; // heap base
      return ptr;
    },

    log(msg: string): void {
      const encoded = encoder.encode(msg);
      const ptr = 0;
      new Uint8Array(memory.buffer, ptr, Math.min(encoded.length, 65536)).set(encoded);
    },

    getConfig(key: string): string | null {
      const outBuf = new Uint8Array(65536);
      return null;
    },

    setState(key: string, value: string): void {
      // Handled by host
    },

    getState(key: string): string | null {
      return null;
    },

    httpRequest(
      method: string,
      url: string,
      body?: string,
      headers?: Record<string, string>,
    ): { status: number; body: string } {
      return { status: 500, body: 'Not available outside host' };
    },

    getAbiVersion(): number {
      return 1;
    },

    getTimeMs(): number {
      return Date.now();
    },

    random(len: number): Uint8Array {
      const arr = new Uint8Array(len);
      crypto.getRandomValues(arr);
      return arr;
    },
  };
}

export function defineTool(
  def: ToolDefinition & {
    execute(args: Record<string, unknown>): Record<string, unknown> | string;
  },
): ToolDefinition & {
  execute(args: Record<string, unknown>): Record<string, unknown> | string;
} {
  return def;
}

export function definePlugin(config: PluginConfig): PluginConfig {
  return config;
}

export function generateCapabilitiesJson(tools: ToolDefinition[]): string {
  return JSON.stringify({
    abi_version: 1,
    tools: tools.map((t) => ({
      name: t.name,
      description: t.description,
      params: t.params.map((p) => ({
        name: p.name,
        type: p.type,
        description: p.description,
        required: p.required ?? false,
      })),
    })),
  });
}

export function generateWasmPluginModule(
  config: PluginConfig,
  toolExecutors: Record<string, (args: Record<string, unknown>) => unknown>,
): string {
  const capsJson = generateCapabilitiesJson(config.tools);

  return `
// Generated by CortexPrism WASM Plugin SDK
// Plugin: ${config.name} v${config.version}

let _capabilitiesJson: string | null = null;
const _encoder = new TextEncoder();
const _decoder = new TextDecoder();

function readStr(ptr: number, len: number): string {
  return _decoder.decode(new Uint8Array(new Uint8Array(0).buffer, ptr, Math.min(len, 65536)));
}

function writeStr(str: string, outPtr: number, outLenPtr: number): void {
  const encoded = _encoder.encode(str);
  const maxLen = Math.min(encoded.length, 65536);
  new Uint8Array(new Uint8Array(0).buffer, outPtr, maxLen).set(encoded.subarray(0, maxLen));
}

export function plugin_get_abi_version(): number {
  return 1;
}

export function plugin_init(): void {
  ${JSON.stringify(capsJson, null, 2)};
}

export function plugin_destroy(): void {
}

export function plugin_get_capabilities(outJsonPtr: number, outLenPtr: number): number {
  const json = ${JSON.stringify(capsJson)};
  writeStr(json, outJsonPtr, outLenPtr);
  return 0;
}

const _executors: Record<string, (args: Record<string, unknown>) => unknown> = ${
    JSON.stringify(Object.keys(toolExecutors))
  };

export function plugin_execute_tool(
  toolNamePtr: number, toolNameLen: number,
  argsJsonPtr: number, argsJsonLen: number,
  outResultPtr: number, outLenPtr: number,
): number {
  try {
    const toolName = readStr(toolNamePtr, toolNameLen);
    const argsJson = readStr(argsJsonPtr, argsJsonLen);
    const args = JSON.parse(argsJson);
    const executor = _executors[toolName];
    if (!executor) {
      writeStr('Unknown tool: ' + toolName, outResultPtr, outLenPtr);
      return -1;
    }
    const result = executor(args);
    const resultJson = typeof result === 'string' ? result : JSON.stringify(result);
    writeStr(resultJson, outResultPtr, outLenPtr);
    return 0;
  } catch (e) {
    writeStr(e.message, outResultPtr, outLenPtr);
    return -1;
  }
}
`;
}
